### ISSUE TITLE
No EXE to run?

### ISSUE THREAD

**Issue by Maxplasma** [DioJoestar/SteamCMD-GUI#15]
https://gyazo.com/ac200cc30d12940d1743e3e02ac0893f

That's pretty much it.

**Comment by DioJoestar** [comment]
You are downloading the source code from GitHub. Go to [releases] (https://github.com/DioJoestar/SteamCMD-GUI/releases/latest) or use a [mirror] (https://github.com/DioJoestar/SteamCMD-GUI#download) from  the readme list.
