### ISSUE TITLE
This strange thing happening

### ISSUE THREAD

**Issue by spectre1999** [DioJoestar/SteamCMD-GUI#16]
Sorry i am a newbie but why is this happening?
![untitled](https://cloud.githubusercontent.com/assets/4442798/12079285/4d4ac09e-b21a-11e5-8026-f625d58a2094.png)

Obs.: Window 7 Professional x64

**Comment by sparkie951** [comment]
I need a little more info here, What are you trying to do, Run a server? Would be glad to help you get it setup.

Don’t worry about being a Newbie.... We all have been there.

Sparkie


From: spectre1999 
Sent: Sunday, January 03, 2016 9:03 AM
To: DioJoestar/SteamCMD-GUI 
Subject: [SteamCMD-GUI] This strange thing happening (#16)

Sorry i am a newbie but why is this happening?


Obs: Window 7 Professional x64

**Comment by spectre1999** [comment]
This time I was trying to run a server but I think that's not the point because I couldn't even start... Actually, it happens almost everytime I'm installing something, you know, happens to a bunch of application setups...

**Comment by sparkie951** [comment]
Do you have Team Speak? may be able to work with you.

**Comment by DioJoestar** [comment]
Not sure but its seems a graphical error of the system for displaying the inputs.

**Comment by sparkie951** [comment]
What server are you trying to run... Insurgency or something else.... I have batch files setup, only requires one line and it does everything... Feel free to copy and edit it... 

As for Teamspeak you can download it at http://www.teamspeak.com/downloads just choose the version that works for you, and you can connect to my teamspeak server and will try to work it through for you.

**Comment by spectre1999** [comment]
Actually I was trying to run a custom one, Hurtworld. And I don't have Teamspeak, maybe I will download it... I'll have to reinstall my operating system because some files got corrupted, so definitely there is something wrong... I'll let you guys know if something changes. Thanks for now!

**Comment by sparkie951** [comment]
Is that a Steam Game???? I do not see it on the list... All of the games that I have found are at: https://developer.valvesoftware.com/wiki/Dedicated_Servers_List

**Comment by spectre1999** [comment]
In fact, it's not on the list but it is a Steam game... But I also tryed with Rust and the same thing happens... Nevermind, as soon as fix my OS I'll try running it again...

**Comment by sparkie951** [comment]
Good deal.. Best of luck to you
