### ISSUE TITLE
What the heck is srcds ??

### ISSUE THREAD

**Issue by Romarain** [DioJoestar/SteamCMD-GUI#30]
In the Run Server tab, there is :

![2021-03-20_01h21m44s_RDCMan](https://user-images.githubusercontent.com/22033256/111853414-2dc5eb80-891b-11eb-8e75-542dfe1a4b60.jpg)

What is it ??

Is this so much asking that you place yourself in the position of users before distributing your product online ?
Jesus Christ, everyday I have several problems due to people locked in their head and not being able to make a feature or a button understandable, or a bug, or something...

**Comment by DioJoestar** [comment]
Read the documentation in the Valve Developer Wiki.

**Comment by Romarain** [comment]
Hey, calm down. I don't have to go read a general documentation about developpment.
It's your duty to create your product correctly so each feature is labelled in order fir user to understand it.
And FYI, this is the tabs I opened in my web browser, for you to see how many google request and pages I've opened just the last night (there was more during the days I past trying to make steamCDM to work) :
![2021-03-20_13h12m40s_chrome](https://user-images.githubusercontent.com/22033256/111869106-fd636900-897d-11eb-9261-b21dfaede620.jpg)

These are tutorials I've read about SteamCMD, **none ever talked about the limitation to games running with SOURCE engine** :
https://developer.valvesoftware.com/wiki/SteamCMD:fr
https://danielgibbs.co.uk/2014/02/steamcmd/

Even those youtube tutorial didn't talk about it : 
https://www.youtube.com/results?search_query=steam+CMD+GUI
https://www.youtube.com/watch?v=WJSKJma_Omw

So just admit that you all are doing a bad job.

**Comment by DioJoestar** [comment]
My duty? No, this was a personal project I did to start learning programming. I owe you nothing for something I did for personal purpose that I decided to share with others.
The software has been used by a lot of people during 6 years and you are the first one to complain about not being correctly. It may be outdated, but isn't hard to understand.

Go keep searching in Google. GL!
