### ISSUE TITLE
recommended tutorial not avaible 

### ISSUE THREAD

**Issue by drachedachte1** [DioJoestar/SteamCMD-GUI#31]

**Comment by ElectronicsArchiver** [comment]
The recommended English tutorial was removed in 4e4534b by @DioJoestar.
Issue should be closed.

**Comment by drachedachte1** [comment]
> The recommended English tutorial was removed in [4e4534b](https://github.com/DioJoestar/SteamCMD-GUI/commit/4e4534b2a3050ab5044a8ff8f627b7007c92014e) by @DioJoestar. Issue should be closed.

so no more tutorials?
and damn that was a old issue godamn

**Comment by ElectronicsArchiver** [comment]
Maybe someone made a new one in the meantime, if you find one, you could open an issue with the link I guess.

Check the new overview btw: https://github.com/DioJoestar/SteamCMD-GUI/blob/master/Documentation/Tutorials.md
