### ISSUE TITLE
Will there be linux support?

### ISSUE THREAD

**Issue by EmeraldShield99** [DioJoestar/SteamCMD-GUI#33]
Recently i was trying to use Steamcmd and its fairly comlicated, so i found this GUI for steam cmd but when i downloaded it it was for windows only.  Is there going to be linux support? specifically arch linux.

**Comment by DioJoestar** [comment]
Theres no plans on making a multiplatform or linux version.

**Comment by the1killer** [comment]
@DioJoestar 
Could this theoretically be done with .Net Core now?

**Comment by AndrSator** [comment]
> @DioJoestar Could this theoretically be done with .Net Core now?

I have no idea, but I think it would only be possible if it was a just console application since there is no MAUI nor Windows Forms on Linux.
