### ISSUE TITLE
[GMOD] Custom Command for Setting the Map does not work

### ISSUE THREAD

**Issue by Scream145** [DioJoestar/SteamCMD-GUI#39]
When setting the map in the Custom Commands section with +map does nothing and loads the server with gm_construct.

**Comment by AndrSator** [comment]
The +map command is already defined in the launch option and takes the input from the Map dropdown.

**Comment by Scream145** [comment]
> The +map command is already defined in the launch option and takes the input from the Map dropdown.

Ah, workshop mods don't add the map to the dropdown list, have to manually extract and place the map inside the maps folder. Thanks!
